import { InputConnectionType } from "../types/InputConnectionType.js";

/**
 * @interface
 */
export class NodeTypeInterface {

	nodeId;
	inConnectors;
	outConnectors;
	formRef;
	componentId;
	aiGenerated;
	importFields;
	minimizedWidth;

	/** This'll is for allowing node counte to propagate as link is created. 
	 * this is be set automatically set and managed by WorkspaceController, 
	 * @type { NodeTypeInterface } */
	nextNode;

	/** @type { NodeTypeInterface } */
	prevNode;

	//State variable
	nodeCount;

	/** Implemented at each node as needed, but the call is automatically
	 *  through WorkspaceController when specific node recieces connection
	 * @param { InputConnectionType<{}> } param0 */
	onInputConnection({ data, type }){}

	/** Implemented at each node as needed, but the call is automatically
	 * through the WorkspaceController when connecting to specific node */
	onOutputConnection(){}

	/** Implemented at each node as needed, but the call is automatically
	 * through the WorkspaceController when connecting to specific node */
	onConectionDelete(){}

	/** This method is being implemented for every nodeType that needs to hold the auto-call
	 *  of onOutputConnection() which notifies the node receiveng connection through
	 *  onInputConnection. Needs to be called according to each node readiness logic
	 *  The implemente code will be Components.emitAction(`nodeReady${this.cmpInternalId}`) */
	notifyReadiness(){}

	/** Implemented at each node as needed. This is this just a signature for guidence.
	 * the idea is for this one to be called whenever a node is generated by the AIAgent*/
	handleAiGenerated(){}

	/** @returns { boolean } */
	validate(){}

}