services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault-config.hcl
    volumes:
      - ./vault-config.hcl:/vault/config/vault-config.hcl
      - vault_data:/vault/file

volumes:
  vault_data:

networks:
  default:
    name: vault_network