API_SOURCE = 'API_SOURCE'
SQL_SOURCE = 'SQL_SOURCE'
FS_SOURCE = 'FS_SOURCE'
S3_SOURCE = 'S3_SOURCE'
CODE_SOURCE = 'CODE_SOURCE'

SQL_DEST = 'SQL_DEST'
CODE_DEST = 'CODE_DEST'
DUCKDB_DEST = 'DUCKDB_DEST'